name: Build Plugins

on: push

jobs:
  build:
    if: ${{ github.repository != 'Artemis-RGB/Artemis.PluginTemplate' && '[ -f .template ]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: dotnet publish -c Release src

      # You'll need to fill in the name of your plugin here
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          path: src/artemis.plugins.timelinestates/bin/x64/release/net8.0/publish
